### ISSUE TITLE
Kotlin 2.0 migration or type-safe-navigation migration or agp version up 진행시 release build 에서 activity 가 포함된 모듈의 클래스들을 참조할 수 없는 이슈

### ISSUE THREAD

**Issue by easyhooon** [Project-Unifest/unifest-android#270]
proguard(난독화)를 비활성화 해도 runtime error 가 발생하여, migration 하여 앱을 업데이트할 수 없는 문제가 발생하고 있음.
무엇이 원인인지 확실히 판단 후(범인 찾기) 해결 필요.

다른 프로젝트에서도 Kotlin 2.0 migration 시 같은 문제가 발생하는 것으로 보아 2.0 migration 과정에서 문제가 발생하는 것으로 판단되는 중
다만 해당 프로젝트는 다시 1.9x version 으로 롤백하면 release build 후 문제가 없으나, unifest 의 경우 Kotlin 버전만 1.9x 로 롤백해도 같은 문제가 발생하여, type-safe-navigation, agp version 도 롤백해줘야 했음.(agp 버전의 문제일 가능성도 존재, ~~type-safe-navigation 은 아무리 생각해도 죄가없음...~~ <- kotlinx-serialization 관련 proguard 문제 존재 )

해결 후 patch version update 진행

**Comment by easyhooon** [comment]
kotlin version 을 그대로 둔채, type-safe-navigation 적용시 proguard 활성화 할 경우 runtime crash 발생
```
of.g: Serializer for class 'p' is not found.
                                                                                                    Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
                                                                                                    
                                                                                                    	at s1.c.U1(Unknown Source:18)
                                                                                                    	at o4.d0.<init>(SourceFile:5)
                                                                                                    	at o4.g0.<init>(SourceFile:2)
                                                                                                    	at b.m.m(Unknown Source:297)
                                                                                                    	at z6.h.a(Unknown Source:588)
                                                                                                    	at r.l1.f(Unknown Source:111)
                                                                                                    	at r.l1.h(Unknown Source:73)
                                                                                                    	at x0.b.a(Unknown Source:45)
                                                                                                    	at x0.b.h(Unknown Source:8)
                                                                                                    	at p.h.e(Unknown Source:122)
                                                                                                    	at p.h.h(Unknown Source:868)
                                                                                                    	at x0.b.a(Unknown Source:45)
                                                                                                    	at x0.b.h(Unknown Source:8)
                                                                                                    	at m0.z2.a(Unknown Source:106)
                                                                                                    	at m0.z2.i(Unknown Source:15)
                                                                                                    	at x0.b.i(Unknown Source:53)
                                                                                                    	at z.k0.a(Unknown Source:638)
                                                                                                    	at z.k0.i(Unknown Source:127)
                                                                                                    	at x0.b.i(Unknown Source:53)
                                                                                                    	at ff.f0.s(Unknown Source:14)
                                                                                                    	at p0.r.q(Unknown Source:200)
                                                                                                    	at p0.y.n(Unknown Source:30)
                                                                                                    	at p0.n2.a(Unknown Source:50)
                                                                                                    	at p0.p.a(Unknown Source:4)
                                                                                                    	at p0.y.o(Unknown Source:8)
                                                                                                    	at x1.i0.i(Unknown Source:29)
                                                                                                    	at x1.i0.h(Unknown Source:121)
                                                                                                    	at x1.d0.i0(Unknown Source:159)
                                                                                                    	at m0.c3.a(Unknown Source:895)
                                                                                                    	at m0.c3.i(Unknown Source:11)
                                                                                                    	at x1.f0.b(Unknown Source:79)
                                                                                                    	at z1.x.e(Unknown Source:37)
                                                                                                    	at z1.n0.b(Unknown Source:93)
                                                                                                    	at z1.n0.c(Unknown Source:1144)
                                                                                                    	at z6.h.P(Unknown Source:55)
                                                                                                    	at z0.a0.a(Unknown Source:47)
                                                                                                    	at z0.c0.d(Unknown Source:135)
                                                                                                    	at z1.u1.a(Unknown Source:2)
                                                                                                    	at z1.o0.E0(Unknown Source:109)
                                                                                                    	at z1.o0.e(Unknown Source:90)
                                                                                                    	at w.u.b(Unknown Source:146)
                                                                                                    	at z1.x.e(Unknown Source:37)
                                                                                                    	at i1.s0.h(Unknown Source:0)
                                                                                                    	at z1.c0.e(Unknown Source:14)
                                                                                                    	at i1.s0.h(Unknown Source:0)
                                                                                                    	at z1.c0.e(Unknown Source:14)
                                                                                                    	at z1.n0.b(Unknown Source:93)
                                                                                                    	at z1.n0.c(Unknown Source:1144)
                                                                                                    	at z6.h.P(Unknown Source:55)
                                                                                                    	at z0.a0.a(Unknown Source:47)
                                                                                                    	at z0.c0.d(Unknown Source:135)
                                                                                                    	at z1.u1.a(Unknown Source:2)
                                                                                                    	at z1.o0.E0(Unknown Source:109)
                                                                                                    	at z1.o0.e(Unknown Source:90)
                                                                                                    	at x1.e1.b(Unknown Source:38)
                                                                                                    	at z1.x.e(Unknown Source:37)
                                                                                                    	at z1.n0.b(Unknown Source:93)
                                                                                                    	at z1.n0.c(Unknown Source:1144)
                                                                                                    	at z6.h.P(Unknown Source:113)
                                                                                                    	at z0.a0.a(Unknown Source:47)
                                                                                                    	at z0.c0.d(Unknown Source:135)
                                                                                                    	at z1.u1.a(Unknown Source:2)
                                                                                                    	at z1.o0.E0(Unknown Source:109)
                                                                                                    	at z1.h0.M(Unknown Source:16)
                                                                                                    	at z1.w0.c(Unknown Source:2)
                                                                                                    	at z1.w0.o(Unknown Source:22)
                                                                                                    	at z1.w0.l(Unknown Source:61)
                                                                                                    	at a2.a0.onMeasure(Unknown Source:122)
                                                                                                    	at android.view.View.measure(View.java:28588)
                                                                                                    	at a2.a.g(Unknown Source:63)
                                                                                                    	at a2.a.onMeasure(Unknown Source:3)
                                                                                                    	at android.view.View.measure(View.java:28588)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at android.view.View.measure(View.java:28588)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
                                                                                                    	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
                                                                                                    	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
                                                                                                    	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
                                                                                                    	at android.view.View.measure(View.java:28588)
                                                                                                    	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
                                                                                                    	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                                                    	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1054)
                                                                                                    	at android.view.View.measure(View.java:28588)
                                                                                                    	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5273)
                                                                                                    	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3660)
                                                                                                    	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4030)
                                                                                                    	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3345)
                                                                                                    	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11437)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1690)
                                                                                                    	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
                                                                                                    	at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
                                                                                                    	at android.view.Choreographer.doFrame(Choreographer.java:1080)
                                                                                                    	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
2024-09-30 14:31:31.802  7917-7917  AndroidRuntime          com.unifest.android                  E  	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9063)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by easyhooon** [comment]
https://github.com/sopt-makers/sopt-android/blob/develop/app/proguard-rules.pro <- kotlinx-serialization 관련 proguard 내용참고

**Comment by easyhooon** [comment]
https://github.com/Nexters/PomoNyang-Android -> 해당 플젝의 경우 똑같이 kotlin 2.0, type-safe-navigation 을 적용한 플젝이나 별다른 프로가드 설정이 존재지않음

**Comment by easyhooon** [comment]
kotlin 버전을 2.0 위로 올리면 agp 버전을 8.2.2 버전 그대로 둘 경우 release 빌드가 정상적으로 수행되는 것을 확인할 수 있음

type-safe-navigation 의 경우 위 상황에서 proguard 을 비활성화하면 release 빌드가 정상적으로 수행되지만, proguard가 활성화 되면 첫번째 덧글과 같은 에러가 발생하면서 앱이 runtiem에 종료됨

**Comment by easyhooon** [comment]
> kotlin version 을 그대로 둔채, type-safe-navigation 적용시 proguard 활성화 할 경우 runtime crash 발생
> 
> ```
> of.g: Serializer for class 'p' is not found.
>                                                                                                     Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
>                                                                                                     
>                                                                                                     	at s1.c.U1(Unknown Source:18)
>                                                                                                     	at o4.d0.<init>(SourceFile:5)
>                                                                                                     	at o4.g0.<init>(SourceFile:2)
>                                                                                                     	at b.m.m(Unknown Source:297)
>                                                                                                     	at z6.h.a(Unknown Source:588)
>                                                                                                     	at r.l1.f(Unknown Source:111)
>                                                                                                     	at r.l1.h(Unknown Source:73)
>                                                                                                     	at x0.b.a(Unknown Source:45)
>                                                                                                     	at x0.b.h(Unknown Source:8)
>                                                                                                     	at p.h.e(Unknown Source:122)
>                                                                                                     	at p.h.h(Unknown Source:868)
>                                                                                                     	at x0.b.a(Unknown Source:45)
>                                                                                                     	at x0.b.h(Unknown Source:8)
>                                                                                                     	at m0.z2.a(Unknown Source:106)
>                                                                                                     	at m0.z2.i(Unknown Source:15)
>                                                                                                     	at x0.b.i(Unknown Source:53)
>                                                                                                     	at z.k0.a(Unknown Source:638)
>                                                                                                     	at z.k0.i(Unknown Source:127)
>                                                                                                     	at x0.b.i(Unknown Source:53)
>                                                                                                     	at ff.f0.s(Unknown Source:14)
>                                                                                                     	at p0.r.q(Unknown Source:200)
>                                                                                                     	at p0.y.n(Unknown Source:30)
>                                                                                                     	at p0.n2.a(Unknown Source:50)
>                                                                                                     	at p0.p.a(Unknown Source:4)
>                                                                                                     	at p0.y.o(Unknown Source:8)
>                                                                                                     	at x1.i0.i(Unknown Source:29)
>                                                                                                     	at x1.i0.h(Unknown Source:121)
>                                                                                                     	at x1.d0.i0(Unknown Source:159)
>                                                                                                     	at m0.c3.a(Unknown Source:895)
>                                                                                                     	at m0.c3.i(Unknown Source:11)
>                                                                                                     	at x1.f0.b(Unknown Source:79)
>                                                                                                     	at z1.x.e(Unknown Source:37)
>                                                                                                     	at z1.n0.b(Unknown Source:93)
>                                                                                                     	at z1.n0.c(Unknown Source:1144)
>                                                                                                     	at z6.h.P(Unknown Source:55)
>                                                                                                     	at z0.a0.a(Unknown Source:47)
>                                                                                                     	at z0.c0.d(Unknown Source:135)
>                                                                                                     	at z1.u1.a(Unknown Source:2)
>                                                                                                     	at z1.o0.E0(Unknown Source:109)
>                                                                                                     	at z1.o0.e(Unknown Source:90)
>                                                                                                     	at w.u.b(Unknown Source:146)
>                                                                                                     	at z1.x.e(Unknown Source:37)
>                                                                                                     	at i1.s0.h(Unknown Source:0)
>                                                                                                     	at z1.c0.e(Unknown Source:14)
>                                                                                                     	at i1.s0.h(Unknown Source:0)
>                                                                                                     	at z1.c0.e(Unknown Source:14)
>                                                                                                     	at z1.n0.b(Unknown Source:93)
>                                                                                                     	at z1.n0.c(Unknown Source:1144)
>                                                                                                     	at z6.h.P(Unknown Source:55)
>                                                                                                     	at z0.a0.a(Unknown Source:47)
>                                                                                                     	at z0.c0.d(Unknown Source:135)
>                                                                                                     	at z1.u1.a(Unknown Source:2)
>                                                                                                     	at z1.o0.E0(Unknown Source:109)
>                                                                                                     	at z1.o0.e(Unknown Source:90)
>                                                                                                     	at x1.e1.b(Unknown Source:38)
>                                                                                                     	at z1.x.e(Unknown Source:37)
>                                                                                                     	at z1.n0.b(Unknown Source:93)
>                                                                                                     	at z1.n0.c(Unknown Source:1144)
>                                                                                                     	at z6.h.P(Unknown Source:113)
>                                                                                                     	at z0.a0.a(Unknown Source:47)
>                                                                                                     	at z0.c0.d(Unknown Source:135)
>                                                                                                     	at z1.u1.a(Unknown Source:2)
>                                                                                                     	at z1.o0.E0(Unknown Source:109)
>                                                                                                     	at z1.h0.M(Unknown Source:16)
>                                                                                                     	at z1.w0.c(Unknown Source:2)
>                                                                                                     	at z1.w0.o(Unknown Source:22)
>                                                                                                     	at z1.w0.l(Unknown Source:61)
>                                                                                                     	at a2.a0.onMeasure(Unknown Source:122)
>                                                                                                     	at android.view.View.measure(View.java:28588)
>                                                                                                     	at a2.a.g(Unknown Source:63)
>                                                                                                     	at a2.a.onMeasure(Unknown Source:3)
>                                                                                                     	at android.view.View.measure(View.java:28588)
>                                                                                                     	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
>                                                                                                     	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
>                                                                                                     	at android.view.View.measure(View.java:28588)
>                                                                                                     	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
>                                                                                                     	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
>                                                                                                     	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
>                                                                                                     	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
>                                                                                                     	at android.view.View.measure(View.java:28588)
>                                                                                                     	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7442)
>                                                                                                     	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
>                                                                                                     	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1054)
>                                                                                                     	at android.view.View.measure(View.java:28588)
>                                                                                                     	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5273)
>                                                                                                     	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3660)
>                                                                                                     	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4030)
>                                                                                                     	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3345)
>                                                                                                     	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11437)
>                                                                                                     	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1690)
>                                                                                                     	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1699)
>                                                                                                     	at android.view.Choreographer.doCallbacks(Choreographer.java:1154)
>                                                                                                     	at android.view.Choreographer.doFrame(Choreographer.java:1080)
>                                                                                                     	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1647)
> 2024-09-30 14:31:31.802  7917-7917  AndroidRuntime          com.unifest.android                  E  	at android.os.Handler.handleCallback(Handler.java:958)
>                                                                                                     	at android.os.Handler.dispatchMessage(Handler.java:99)
>                                                                                                     	at android.os.Looper.loopOnce(Looper.java:230)
>                                                                                                     	at android.os.Looper.loop(Looper.java:319)
>                                                                                                     	at android.app.ActivityThread.main(ActivityThread.java:9063)
>                                                                                                     	at java.lang.reflect.Method.invoke(Native Method)
>                                                                                                     	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
>                                                                                                     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
> ```

해당 에러에 대해 R8 retrace 를 해볼 필요가 있음

**Comment by easyhooon** [comment]
> kotlin 버전을 2.0 위로 올리면 agp 버전을 8.2.2 버전 그대로 둘 경우 release 빌드가 정상적으로 수행되는 것을 확인할 수 있음
type-safe-navigation 의 경우 위 상황에서 proguard 을 비활성화하면 release 빌드가 정상적으로 수행되지만, proguard가 활성화 되면 첫번째 덧글과 같은 에러가 발생하면서 앱이 runtiem에 종료됨

다만 agp 버전 8.2.2, k2 compiler 일 경우, compose preview tap 이 보이지 않는 문제 발생(IDE 우측 상단에 preview layout 버튼이 사라짐, 따라서 preview 를 확인할 수 없음)
agp 버전 8.5.2 버전 이렇게 올리면 다시 compose preview 탭이 활성화되는 것을 확인

CommonExtension(AndroidExtension) 관련해서 충돌이 발생하는 듯함 k2 compiler 를 적용했을 때 문제가 없는 최소 agp 버전이 존재한다던지(CommonExtension * 의 수가 5개에서 6개로 늘어나는 시점일 것으로 추측)
